# do-try
Catches errors and rejected promises, returns tuple
